version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    expose:
      - "5000"
    ports:
      - "5000:5000"  # Keep this for direct access if needed
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped