version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=True
    command: /bin/bash -c "cd /app/backend && python app.py run"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      target: build  # Stop at build stage for development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    command: npm start